// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NMStest2.Models;

namespace NMStest2.Migrations
{
    [DbContext(typeof(NMStest2Context))]
    [Migration("20190412154624_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NMStest.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasAcientBones");

                    b.Property<bool>("HasSalvageScrap");

                    b.Property<string>("PlanetName");

                    b.Property<string>("Sentinels");

                    b.Property<int>("SystemId");

                    b.HasKey("PlanetId");

                    b.HasIndex("SystemId");

                    b.ToTable("Planet");
                });

            modelBuilder.Entity("NMStest.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlanetId");

                    b.Property<int>("foreignKey");

                    b.Property<string>("resourceName");

                    b.HasKey("ResourceId");

                    b.HasIndex("PlanetId");

                    b.ToTable("Resource");
                });

            modelBuilder.Entity("NMStest.Models.StarSystems", b =>
                {
                    b.Property<int>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConflictType");

                    b.Property<string>("EconomyType");

                    b.Property<string>("StarType");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SystemId");

                    b.ToTable("StarSystems");
                });

            modelBuilder.Entity("NMStest.Models.Planet", b =>
                {
                    b.HasOne("NMStest.Models.StarSystems", "StarSystem")
                        .WithMany("ListPlanets")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NMStest.Models.Resource", b =>
                {
                    b.HasOne("NMStest.Models.Planet")
                        .WithMany("ListResources")
                        .HasForeignKey("PlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
